=== yrodrigez/daaexample-1516-yrlorenzo/src/test/resources/datasets/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (people*, users*, pets*)>
<!ELEMENT people EMPTY>
<!ELEMENT users EMPTY>
<!ELEMENT pets EMPTY>
<!ATTLIST people
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    surname CDATA #IMPLIED
>
<!ATTLIST users
    login CDATA #IMPLIED
    password CDATA #IMPLIED
>
<!ATTLIST pets
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    breed CDATA #IMPLIED
    animal CDATA #IMPLIED
    owner_id CDATA #IMPLIED
>

=== yrodrigez/daaexample-1516-yrlorenzo/src/test/resources/datasets/pets/dataset-modify.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../dataset.dtd">

<dataset>
	<people id="1" name="Antón" surname="Álvarez" />
	<people id="2" name="Ana" surname="Amargo" />
	<people id="3" name="Manuel" surname="Martínez" />
	<people id="4" name="María" surname="Márquez" />
	<people id="5" name="Lorenzo" surname="López" />
	<people id="6" name="Laura" surname="Laredo" />
	<people id="7" name="Perico" surname="Palotes" />
	<people id="8" name="Patricia" surname="Pérez" />
	<people id="9" name="Julia" surname="Justa" />
	<people id="10" name="Juan" surname="Jiménez" />

	<users login="admin" password="0b893644f3b2097d004c58d585e784ac92dd1356d25158a298573ad54ab2d15d" />

	<pets id="1" name="Whisky" breed="Beagle" animal="Dog" owner_id="1" />
	<pets id="2" name="Perroman" breed="Doberman" animal="Dog" owner_id="4" />
	<pets id="3" name="unPerro" breed="doberman" animal="perro" owner_id="1" />
	<pets id="4" name="Perro3" breed="Gray" animal="Rhino" owner_id="2" />
	<pets id="5" name="Perro3" breed="Gray" animal="Rhino" owner_id="5" />
</dataset>
